hmcts/terraform-module-virtual-machine

- 008-variables.tf
- 020-networking.tf
> feat: added option to specify DNS servers

- README.md
- inputs-optional.tf
- interpolated-defaults.tf
- main.tf
> feat: added configurable identity

- main.tf
see comments in code
tested locally and I get further now
> Add computer name for Windows

- main.tf
Linux supports ImageDefault so we don't need to do it there.
Possibly could extend this to 2019, but just being conservative for now.
This could be made configurable if someone has a requirement for it.
Tested locally and I can get further
> Autodetect patch_assessment_mode for Windows 2022

- README.md
- example/main.tf
- inputs-optional.tf
- inputs-required.tf
- main.tf
Please remove this line and everything above and fill the following sections:
https://github.com/hmcts/pre-shared-infrastructure/pull/518
https://github.com/hmcts/martha-infra/pull/62
https://tools.hmcts.net/jira/browse/DTSPO-14095
https://tools.hmcts.net/jira/browse/DTSPO-14094
Fixes https://github.com/hmcts/terraform-module-virtual-machine/issues/19
Fixes https://github.com/hmcts/terraform-module-virtual-machine/issues/24
Fix Availability Zones variable - Typo
Privateip-allocation variable default to dynamic
```
[ ] Yes
[x ] No
```
> Dtspo 14094

- README.md
- example/main.tf
- inputs-optional.tf
- inputs-required.tf
- main.tf
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> Revert "Dtspo 14094"

- README.md
- outputs.tf
N/A
Update module output to include private IP address.
```
[ ] Yes
[x] No
```
> feat: added network interface private ip to module outputs

- README.md
- extensions.tf
- inputs-optional.tf
- provider.tf
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
changes made for bootstrap test VM repo https://github.com/hmcts/Boostrap-test-vm
```
[ ] Yes
[ ] No
```
> DTSPO-14772 - changes made for bootstrap test VM

- README.md
- extensions.tf
- inputs-optional.tf
- inputs-required.tf
https://tools.hmcts.net/jira/browse/DTSPO-14774
Pass the environment value to the bootstrap module
```
[ ] Yes
[X] No
```
> Add-env-variable

- README.md
- inputs-optional.tf
- main.tf
N/A
Specify OS disk size - defaults to 128GB
```
[ ] Yes
[x] No
```
> feat: added ability to specify os disk size

- main.tf
*
Corrected computer_name_calculated value.
> Corrected computer_name_calculated value.

- README.md
- extensions.tf
- inputs-optional.tf
https://tools.hmcts.net/jira/browse/DTSPO-17780
Added new optional variable needed for run command extenstion
> DTSPO-17780 - Added new var needed for run command extension

- extensions.tf
- inputs-optional.tf
- interpolated-defaults.tf
- networking.tf
- outputs.tf
- tests/locals.tftest.hcl
- tests/networking.tftest.hcl
- tests/vm_name.tftest.hcl
- tests/vm_type.tftest.hcl
https://tools.hmcts.net/jira/browse/DTSPO-18758
Adding xdr tags input to vm bootstrap module call, setting to same value as existing tags input
> Adding xdr tags input to vm bootstrap module call, setting to same value as existing tags input

- outputs.tf
Adding conditional to xdr tags output
> Adding condition to xdr_tags output

- README.md
- example/main.tf
- example/provider.tf
- extensions.tf
- networking.tf
- provider.tf
- tests/locals.tftest.hcl
- tests/networking.tftest.hcl
- tests/vm_name.tftest.hcl
- tests/vm_type.tftest.hcl
Reverts hmcts/terraform-module-virtual-machine#54
> Revert "DTSPO-18803-Migrate-Glimr-servers-to-AMA"

- README.md
- extensions.tf
- inputs-optional.tf
Add Docker install boolean option to pass to Bootstrap module call
> Adding docker inputs for bootstrap

- README.md
- extensions.tf
- inputs-optional.tf
https://tools.hmcts.net/jira/browse/DTSPO-24689 
- Allows to pass the default variable from all the consumers, its already has the same default value so shouldn't cause any issue
> DTSPO-24689 - allows to pass SOC resource group and name

- README.md
- extensions.tf
- inputs-optional.tf
- interpolated-defaults.tf
https://tools.hmcts.net/jira/browse/DTSPO-24943
- Creates optional extension for Linux VMs to allow SSH to Linux VMs
- Assigns SystemAssign Identity if the optional value set to true
- Creates the role assignment resource for the the extension too
> DTSPO-24943 - create AADSSHLoginForLinux exetension

- README.md
- azure-pipelines.yaml
- extensions.tf
- inputs-optional.tf
- Adding optional input for `remove_splunk_uf` to allow teams to override the default value of `true`
- Useful for any VMs that don't use our custom script extension
- Also updating agent image to Ubuntu 24.04 as old image has been removed
> Add optional value to remove splunk UF

- azure-pipelines.yaml
See [DTSPO-26377](https://tools.hmcts.net/jira/browse/DTSPO-26377)
Adds terraform installer task before running terraform commands.
Ran pipeline successfully - https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=854222&view=results
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> fix: add terraform installer task
